// Kmonn Shuna Grand Lance (planned for unreleased SWWM Iridium)
// Slot 0, spawns shared with Ynykron Artifact

Class GrandSpear : MagAmmo
{
	Default
	{
		Tag "$T_GRANDSPEAR";
		Inventory.PickupMessage "$T_GRANDSPEAR";
		Inventory.Icon "graphics/HUD/Icons/A_GrandSpear.png";
		MagAmmo.ParentAmmo "GrandAmmo";
		MagAmmo.ClipSize 5;
		Inventory.MaxAmount 10;
		Inventory.InterHubAmount 10;
		+FLOATBOB;
		FloatBobStrength 0.25;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}

Class GrandAmmo : Ammo
{
	Mixin SWWMAmmo;
	Mixin SWWMOverlapPickupSound;
	Mixin SWWMUseToPickup;

	Default
	{
		Tag "$T_GRANDAMMO";
		Inventory.PickupMessage "$T_GRANDAMMO";
		Stamina 1200000;
		Inventory.Icon "graphics/HUD/Icons/A_RayAmmo.png";
		Inventory.Amount 1;
		Inventory.MaxAmount 2;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 6;
		Ammo.DropAmount 1;
		+FLOATBOB;
		FloatBobStrength 0.25;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}

Class GrandLance : SWWMWeapon
{
	int clipcount;

	Property ClipCount : clipcount;

	Default
	{
		Tag "$T_GRANDLANCE";
		Inventory.PickupMessage "$I_GRANDLANCE";
		Obituary "$O_GRANDLANCE";
		Inventory.Icon "graphics/HUD/Icons/W_GrandLance.png";
		Weapon.SlotNumber 0;
		Weapon.SlotPriority 2.;
		Weapon.SelectionOrder 8000;
		Weapon.AmmoType1 "GrandAmmo";
		Weapon.AmmoGive1 1;
		SWWMWeapon.DropAmmoType "GrandAmmo";
		GrandLance.ClipCount 5;
		Stamina 4200000;
		+SWWMWEAPON.NOFIRSTGIVE;
		+WEAPON.BFG;
		+WEAPON.EXPLOSIVE;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}

