// Kmonn Shuna Quadravol (from UnSX series, not a Quadshot reskin anymore)
// Slot 6, spawns shared with Hellblazer

Class Quadravol : SWWMWeapon
{
	int clipcount;
	int chargelevel;

	Property ClipCount : clipcount;

	Default
	{
		//$Title Quadravol
		//$Group Weapons
		//$Sprite graphics/HUD/Icons/W_Quadravol.png
		//$Icon weapon
		Tag "$T_QUADRAVOL";
		Inventory.PickupMessage "$I_QUADRAVOL";
		Obituary "$O_QUADRAVOL";
		Inventory.Icon "graphics/HUD/Icons/W_Quadravol.png";
		Weapon.SlotNumber 6;
		Weapon.SlotPriority 2.;
		Weapon.SelectionOrder 650;
		Weapon.AmmoType1 "QuadravolAmmo";
		Weapon.AmmoGive1 1;
		SWWMWeapon.DropAmmoType "QuadravolAmmo";
		Quadravol.ClipCount 10;
		Stamina 80000;
		+SWWMWEAPON.NOFIRSTGIVE;
		+WEAPON.EXPLOSIVE;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}
