// Tach-Engine Technologies EMP Rail Carbine (planned for unreleased Zanaveth Ultra Suite 2, successor to EMP Rifle from first Ultra Suite)
// Slot 8, shared spawn with Silver Bullet JET

Class EMPCarbine : SWWMWeapon
{
	int clipcount;
	bool chambered;
	bool initialized;

	Property ClipCount : clipcount;

	Default
	{
		Tag "$T_EMPCARBINE";
		Inventory.PickupMessage "$I_EMPCARBINE";
		Obituary "$O_EMPCARBINE";
		Inventory.Icon "graphics/HUD/Icons/W_EMPCarbine.png";
		Weapon.SlotNumber 8;
		Weapon.SlotPriority 2.;
		Weapon.SelectionOrder 850;
		Weapon.AmmoType1 "EMPCore";
		Weapon.AmmoGive1 1;
		SWWMWeapon.SwapWeapon "SilverBullet";
		SWWMWeapon.DropAmmoType "EMPCore";
		EMPCarbine.ClipCount 4;
		Stamina 500000;
		+SWWMWEAPON.NOFIRSTGIVE;
		+WEAPON.EXPLOSIVE;
		+WEAPON.ALT_AMMO_OPTIONAL;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}
