// All DLC weapon ammo pickups

Class SMW05Ammo : Ammo
{
}

Class SMW05SmallAmmo : SMW05Ammo
{
}

Class SMW05BigAmmo : SMW05Ammo
{
}

Class SheenAmmo : Ammo
{
}

Class SheenSmallAmmo: SheenAmmo
{
}

Class SheenBigAmmo : SheenAmmo
{
}

Class QuadravolAmmo : Ammo
{
}

Class QuadravolPack : QuadravolAmmo
{
}

Class DarkCanister : Ammo
{
}

Class EMPCore : Ammo
{
}

Class EMPCoreBundleSpawn : Actor
{
}

Class RayBolt : MagAmmo
{
}

Class RayAmmo : Ammo
{
}
